name: firebase_storage_example
description: Demonstrates how to use the firebase_storage plugin.

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  firebase_core: ^2.18.0
  firebase_storage: ^11.3.0
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+4
  image_picker_for_web: ^2.1.12

flutter:
  uses-material-design: true
  assets:
    - assets/hello.txt
