name: firebase_in_app_messaging_example
description: Demonstrates how to use the firebase_in_app_messaging plugin.
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  firebase_analytics: ^11.0.1
  firebase_core: ^3.1.0
  firebase_in_app_messaging: ^0.8.0+1
  firebase_in_app_messaging_platform_interface: ^0.2.4+37
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
