name: firebase_database_web
description: The web implementation of firebase_database
version: 0.2.5+9
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_database/firebase_database_web

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  collection: ^1.18.0
  firebase_core: ^3.1.0
  firebase_core_web: ^2.17.2
  firebase_database_platform_interface: ^0.2.5+37
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  firebase_core_platform_interface: ^5.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseDatabaseWeb
        fileName: firebase_database_web.dart
